services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - db

  astro:
    build: ./astro
    ports:
      - "4321:4321"
    volumes:
      - ./astro:/app
    command: npm run dev
    working_dir: /app

volumes:
  db_data:
